### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Mukkod** [Plutoberth/SonyHeadphonesClient#101]
Ive downloaded the program and attempted to connect to my XM5's and that doesnt connect. ive also tried my HT-CT260H which thinks about connecting for a second and then gives the same error. 

the error is simple in description:

Errors:
Couldn't connect: 10049

I understand that XM5 support may not be a thing and if not id love to see it. the CT260H is a sound bar so that might not actually have any settings to fiddle with.

**Comment by Az1977** [comment]
Hi, I also have the same issue - XM5 will not connect.  Is this something that the team are planning?

**Comment by Plutoberth** [comment]
Sadly this is not planned as I don't have the XM5s nor the time to develop the feature, and is already documented in #29.
