### ISSUE TITLE
Add opportunity to upload custom Default Notification Sounds instead existed ones

### ISSUE THREAD

**Issue by sashkyn** [Plutoberth/SonyHeadphonesClient#104]
Hey 👋 

Official mobile app allows to users download Notification Sounds in any languages and somehow to upload it via Bluetooth directly on Headphones.

I've just wanted to ask. Is it possible to implement feature to upload new sounds? How hard is it?

The Main Goal - upload silent and short sounds instead existed ones - I suppose its only way to remove it from Headphones at all 😄

**Comment by semvis123** [comment]
It can be done, although it requires a quite complicated manual proces, see #35

**Comment by sashkyn** [comment]
@semvis123 Thanks! I see...
I'm closing that one
