### ISSUE TITLE
TempleOS not supported (not serious)

### ISSUE THREAD

**Issue by TopchetoEU** [Plutoberth/SonyHeadphonesClient#118]
Hello, fellow human

As a TempleOS user, I am DEEPLY offended that yet another application REFUSES to support my platform of choice. Furthermore, not supporting god's OS is absolutely a deadly sin. Please, add support to TempleOS IMMEDIATELY, or you will have to pay a great price, in the afterlife.

/j

**Comment by Plutoberth** [comment]
TempleOS doesn't support Bluetooth, so this is unplanned.
