### ISSUE TITLE
Option to turn off NC and ambient sound

### ISSUE THREAD

**Issue by quantumfrost** [Plutoberth/SonyHeadphonesClient#18]
Really like the program, but I don't see any option to turn off both NC and ambient sound. It's useful if you want to save battery on the headphones. In the Android app, you can do this by turning off the "Ambient Sound Control" toggle.

![nc_asm_off](https://user-images.githubusercontent.com/4280297/95109490-a7ba3d80-070a-11eb-8002-e7322e049724.jpg)

**Comment by Plutoberth** [comment]
This is definitely possible. I remember doing this accidentally during testing, but I don't remember how I played with the parameters to make it happen (should be fairly trivial). I'm pretty busy now though, so it'll probably take a while until this is implemented if no one else takes it.

**Comment by guilhermealbm** [comment]
I'm working on it!
