### ISSUE TITLE
How can I reverse engineer my headphone to feature to the app?

### ISSUE THREAD

**Issue by ViniDalvino** [Plutoberth/SonyHeadphonesClient#20]

**Comment by Plutoberth** [comment]
Hi,

If you're interested I can share the research repository with you. It's basically a decompiled version of the app with many comments and names (they ran ProGuard on the app, so almost all names have been stripped).

**Comment by miaachan** [comment]
> 
> 
> Hi,
> 
> If you're interested I can share the research repository with you. It's basically a decompiled version of the app with many comments and names (they ran ProGuard on the app, so almost all names have been stripped).

I am also interested!

**Comment by ViniDalvino** [comment]
I am interested. @Plutoberth

**Comment by BenConstable9** [comment]
I am interested as well if this is available?

**Comment by Plutoberth** [comment]
After further consideration I've decided not to test Sony's legal team. If you want, you can do this yourself - I just decompiled it using jd-gui, and then exported the text files for easier work in IntelliJ. The protocol is documented as code in this repository. Additional commands would be implemented similarly to the function [serializeNcAndAsmSetting](https://github.com/Plutoberth/SonyHeadphonesClient/blob/master/Client/CommandSerializer.cpp#L174), for example.
