### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by Eleutherios0** [Plutoberth/SonyHeadphonesClient#26]
The program works very well, it would be nice if you add a shortcut with the new update

**Comment by Plutoberth** [comment]
Do you mean a desktop shortcut? You can just place the program wherever you'd like, and then `Right click` --> `Send to` --> `Desktop`.

**Comment by Eleutherios0** [comment]
No I didn't mean that.  For example, pressing the num1 key while I'm in the game and going into ambient mode

**Comment by Plutoberth** [comment]
Ahhhhh got it. I'm not sure how I can capture keys globally (I saw something about it in imGUI, but I think that it's not mature) and there are more important issues, so I'm not going to implement it (at least in the near future).

**Comment by Eleutherios0** [comment]
Thank you for making this application

**Comment by semvis123** [comment]
System tray functionality could be added to get similar experience as the macOS, but this can not be controlled by keyboard shortcuts.

For example:
https://github.com/zserge/tray

**Comment by Plutoberth** [comment]
not planning to do this, sorry :(
