### ISSUE TITLE
[macOS] Catch exceptions that happen in the bluetooth thread, for example when rfcomm channel can't be opened

### ISSUE THREAD

**Issue by semvis123** [Plutoberth/SonyHeadphonesClient#32]
Currently it fails to catch the error that happen when it connects for example.
This is because the connection happens in a different thread, when the recoverableException is thrown from that thread, it doesn't get catched and thus crashes the client.

This could be solved by passing an error handler to the bluetoothConnector, but I can't get that to work.
My approach was to have a `void` that gets defined in `MacOSBluetoothConnector::MacOSBluetoothConnector`, but that gives an error at compilation: `Reference to non-static member function must be called `.

Used code:
```cpp
// macosbluetoothconnector.mm
MacOSBluetoothConnector::MacOSBluetoothConnector(void (&errorCallback)(RecoverableException))
{
    this->errorHandler = errorCallback;
}
```
```cpp
// macosbluetoothconnector.h
private:
    void *rfcommDevice;
    void *rfcommchannel;
    std::thread* uthread = NULL;
    void errorHandler(RecoverableException);
```

**Comment by Plutoberth** [comment]
Hi,
I have a solution for your problem which also solves an issue where your code doesn't follow the IBluetoothConnector contract. The contract stipulates that `connect` must block until the connection is satisfied.

You can solve this using `std::promise`. You can create an `std::promise<void>` in `connect`, take its future, and then move it into the new thread. In the new thread you can set_value of the promise (with nothing), or `set_exception` if it's needed. Back in `connect`, you can `get` the future. This will wait until the promise is resolved and propagate the exception if one was set.
