### ISSUE TITLE
github action for macOS

### ISSUE THREAD

**Issue by Plutoberth** [Plutoberth/SonyHeadphonesClient#42]
I set up Actions for Linux and Windows so that we have automatic builds on all platforms :)

Sadly, I'm not sure how to do it for mac and I don't have a local env to test stuff anyway. Any chance you could help on this, @semvis123 ?

**Comment by Plutoberth** [comment]
Looks like this might be a good fit - https://github.com/marketplace/actions/xcodebuild-action

**Comment by semvis123** [comment]
Got it working!
I accidentally added it to the other pull request (#37), hope that's not a problem.

**Comment by Plutoberth** [comment]
Awesome! I really like this feature.
