### ISSUE TITLE
Manjaro Support

### ISSUE THREAD

**Issue by alt-glitch** [Plutoberth/SonyHeadphonesClient#49]
Hi, while trying to run the tool I get the error
`./SonyHeadphonesClient: error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory
`
even though I have the shared library installed. 
I am running on Manjaro Linux.

How can I get it to work?

**Comment by Yesterday17** [comment]
You can just install `glew-2.1` package on AUR

**Comment by SayantanRC** [comment]
I am having the same issue on Linux Mint. There is no package named `glew-2.1` in apt.
