### ISSUE TITLE
Arch - could not connect to bluetooth socket

### ISSUE THREAD

**Issue by Mhsbrian** [Plutoberth/SonyHeadphonesClient#53]
Running Arch here, got past the glew 2.1 errors originally and now the application runs fine as expected but when I select WF-1000XM4 I receive "Could not connect to bluetooth socket"

Bluez-git 5.60
bluetooth-support 1-3
bluez-qt 5.84

![image](https://user-images.githubusercontent.com/9922368/127174892-4b1a6002-2d59-43d0-b67a-817e3239ac78.png)

Tried a few things but can't seem to get past this point but no luck, suggestions?

**Comment by semvis123** [comment]
The WF-1000XM4's are currently unsupported, because it uses a different protocol.

**Comment by Mhsbrian** [comment]
> The WF-1000XM4's are currently unsupported, because it uses a different protocol.

Ah,

Understood, thank you much for the quick reply. 

Looking forward to seeing this improve, good work!

**Comment by maxlath** [comment]
for the record, same error with the MDR-1000X model
