### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Plutoberth** [Plutoberth/SonyHeadphonesClient#7]
Please react to this issue if you want Linux support

**Comment by jntnl42** [comment]
I'll try to work on it this weekend!

**Comment by Plutoberth** [comment]
@jntnl42 

Hey - please note: IBluetoothConnector has been changed.

- virtual void disconnect() noexcept(false) = 0;
+ virtual void disconnect() noexcept = 0;

I'll be pushing these changes to master in a bit, so you can just update from there.

**Comment by alexryndin** [comment]
Linux has bluetoothctl, which can be used (afaik) to send raw data to bluetooth device.
Could somebody describe protocol so I could try to use bluetoothctl to tweak device?
I mean, which data sequence should I send and what response should I expect.

**Comment by Plutoberth** [comment]
@alexryndin I built the program so that people that want to add a new platform only have to copy a file from Dear Imgui and implement an interface for Bluetooth communication, so you don't actually need to understand the protocol. However, jimzrt has already implemented a Linux version! I'm just waiting for a couple of fixes and then it'll be merged.

**Comment by alexryndin** [comment]
@Plutoberth your software is great!
I just trying to go deeper and understand the protocol and commands and maybe create something like simplest bash script to control XM4 over d-bus or something. The problem is that I'm a total noob in bluetooth and dbus.

**Comment by Plutoberth** [comment]
> 
> 
> @Plutoberth your software is great!
> I just trying to go deeper and understand the protocol and commands and maybe create something like simplest bash script to control XM4 over d-bus or something. The problem is that I'm a total noob in bluetooth and dbus.

Ahh, I see. Well, the format itself is documented in the CommandSerializer class, everything you need is there. Although some people have reported issues with the XM4, so it could take some time to adapt it.

**Comment by Plutoberth** [comment]
Added by jimzrt and merged :)
