### ISSUE TITLE
Bugfix: "Lazy" virus threat detection

### ISSUE THREAD

**Issue by S34NN** [Plutoberth/SonyHeadphonesClient#80]
I assume this is a false positive, but just wanted to share this as this has caused some frustratiion to work around. Have used the client successfully over the past couple months with no issues. Detected via Bitdefender as Gen:Variant.Lazy.257289 on one of my PCs. 

Uploaded the exe to VirusTotal:

https://www.virustotal.com/gui/file/682ff442842d0cf314151aa511646be748d0c970a7145f6e34f938958d066b30/detection

**Comment by Plutoberth** [comment]
Hmmm, looks like this is due to some resource allocation issue... Might be worth looking at.

**Comment by Plutoberth** [comment]
Not planning to fix this for now, might go away with qt version
