### ISSUE TITLE
Windows 11 (win64.exe)

### ISSUE THREAD

**Issue by janek9971** [Plutoberth/SonyHeadphonesClient#83]
Hi,

I have WH1000XM5 headphones, i tried to connect but i always get the same WSA error.

Here is the screen with the issue.
![image](https://user-images.githubusercontent.com/10576321/202924782-44745963-1658-49c1-b80e-1d51f04de0b8.png)

Is something block to connect to headphones or it is just the problem that this soft doesn't work with WH1000XM5?

**Comment by Plutoberth** [comment]
I'm pretty sure that this is an incompatibility with the WH-1000-XM5s, sorry :(
See the headset reports issue
