### ISSUE TITLE
How Can I change AAC Codec to LDAC via client ?

### ISSUE THREAD

**Issue by aljustiet** [Plutoberth/SonyHeadphonesClient#87]

**Comment by Guy293** [comment]
Not possible as Windows doesn't support LDAC.
But there's an alternative driver you can try:
https://www.reddit.com/r/headphones/comments/zo9czw/now_you_can_try_ldac_96_khz_on_windows_1011/

**Comment by aljustiet** [comment]
I use Mac.

**Comment by aljustiet** [comment]
> Not possible as Windows doesn't support LDAC.
> But there's an alternative driver you can try:
> https://www.reddit.com/r/headphones/comments/zo9czw/now_you_can_try_ldac_96_khz_on_windows_1011/

I use Mac.
