### ISSUE TITLE
Port features of GadgetBridge

### ISSUE THREAD

**Issue by mrmotallebi** [Plutoberth/SonyHeadphonesClient#99]
Wonderful application. It would become more handy if you could port the features implemented by [GadgetBridge](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/sony/headphones) (itself mimicking Sony's official app). 
Opening this issue just as a reference point. Feel free to close it if it's out of scope.

**Comment by Plutoberth** [comment]
Closing for now, but thanks for letting me know.
